import Head from 'next/head'
import { Inter } from 'next/font/google'
import Hero from '@/components/Hero'
import Stat from '@/components/Stat'
import WhyChooseUs from '@/components/WhyChooseUs'
import Review from '@/components/Review'
import VisaInfo from '@/components/VisaInfo'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Prime Travels</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Stat />
      <WhyChooseUs />
      <VisaInfo />
      <Review />
    </>
  )
}
